export {addForStorage} from './addForStorage';
export {addNewTodo} from './addNewTodo';
export {newTodo} from './newTodo';
export {drawNewTodo} from './drawNewTodo';
export {doneTodo} from './doneTodo';
export {removeTodo} from './removeTodo';
export {quantityOfTodo} from './quantityOfTodo';
export {addRemoveBtn} from './addRemoveBtn';
export {hideRemoveBtn} from './hideRemoveBtn';